name: Build Docker Image

on:
  push:
    branches:
    - "!*"
    - "refs/pull/*"
    tags:
    - "!*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quay.io/repository/shota_sawada/php-web-app:latest

